spring:
  application:
    name: message-app
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:5432/chat-app
    username: larryck
    password: L@rr21003

  hikari:
    maximum-pool-size: 20
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        highlight_sql: true
      type:
        preferred_uuid_jdbc_type: VARCHAR

logging:
  level:
    "[org.springframework.messaging]": trace

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
